
export const translations = {
  "my_account": {
    "pt-PT": "Minha Conta",
    "pt-BR": "Minha Conta",
    "en-US": "My Account",
    "es-ES": "Mi Cuenta",
    "fr-FR": "Mon Compte",
    "de-DE": "Mein Konto",
    "it-IT": "Il Mio Account",
    "ja-JP": "マイアカウント",
    "zh-CN": "我的账户",
    "ru-RU": "Мой аккаунт",
    "ar-SA": "حسابي",
    "hi-IN": "मेरा खाता",
    "ko-KR": "내 계정",
    "he-IL": "החשבון שלי",
    "uk-UA": "Мій акаунт",
    "id-ID": "Akun Saya",
    "th-TH": "บัญชีของฉัน"
  },
  "driver_online_status_title": {
    "pt-PT": "Estado Online",
    "pt-BR": "Status Online",
    "en-US": "Online Status",
    "es-ES": "Estado en línea",
    "fr-FR": "Statut en ligne",
    "de-DE": "Online-Status",
    "it-IT": "Stato online",
    "ja-JP": "オンラインステータス",
    "zh-CN": "在线状态",
    "ru-RU": "Онлайн-статус",
    "ar-SA": "الحالة على الإنترنت",
    "hi-IN": "ऑनलाइन स्थिति",
    "ko-KR": "온라인 상태",
    "he-IL": "סטטוס מחובר",
    "uk-UA": "Онлайн-статус",
    "id-ID": "Status Online",
    "th-TH": "สถานะออนไลน์"
  },
  "driver_online_status_desc_offline": {
    "pt-PT": "Seu perfil está invisível para os passageiros. Toque para ficar online.",
    "pt-BR": "Seu perfil está invisível para os passageiros. Toque para ficar online.",
    "en-US": "Your profile is invisible to passengers. Tap to go online.",
    "es-ES": "Tu perfil es invisible para los pasajeros. Toca para conectarte.",
    "fr-FR": "Votre profil est invisible pour les passagers. Appuyez pour vous connecter.",
    "de-DE": "Ihr Profil ist für Passagiere unsichtbar. Tippen Sie, um online zu gehen.",
    "it-IT": "Il tuo profilo è invisibile ai passeggeri. Tocca per andare online.",
    "ja-JP": "あなたのプロフィールは乗客には見えません。タップしてオンラインになります。",
    "zh-CN": "您的个人资料对乘客不可见。点击即可上线。",
    "ru-RU": "Ваш профиль невидим для пассажиров. Нажмите, чтобы выйти в сеть.",
    "ar-SA": "ملفك الشخصي غير مرئي للركاب. انقر لتصبح متصل بالإنترنت.",
    "hi-IN": "आपकी प्रोफ़ाइल यात्रियों के लिए अदृश्य है। ऑनलाइन जाने के लिए टैप करें।",
    "ko-KR": "귀하의 프로필이 승객에게 보이지 않습니다. 탭하여 온라인으로 전환하세요.",
    "he-IL": "הפרופיל שלך בלתי נראה לנוסעים. הקש כדי להתחבר.",
    "uk-UA": "Ваш профіль невидимий для пасажирів. Натисніть, щоб перейти в онлайн.",
    "id-ID": "Profil Anda tidak terlihat oleh penumpang. Ketuk untuk beralih ke mode offline.",
    "th-TH": "โปรไฟล์ของคุณมองไม่เห็นสำหรับผู้โดยสาร แตะเพื่อออนไลน์"
  },
  "Category_accessible_desc ": {
    "pt-PT": "Esta categoria inclui veículos com funcionalidades de acessibilidade.",
    "pt-BR": "Esta categoria inclui veículos com recursos de acessibilidade.",
    "en-US": "This category includes vehicles with accessibility features.",
    "es-ES": "Esta categoría incluye vehículos con características de accesibilidad.",
    "fr-FR": "Cette catégorie inclut les véhicules avec des fonctionnalités d'accessibilité.",
    "de-DE": "Diese Kategorie umfasst Fahrzeuge mit Barrierefreiheitsfunktionen.",
    "it-IT": "Questa categoria include veicoli con funzionalità di accessibilità.",
    "ja-JP": "このカテゴリーには、バリアフリー機能を持つ車両が含まれます。",
    "zh-CN": "此类车辆具备无障碍功能。",
    "ru-RU": "В эту категорию входят транспортные средства с функциями доступности.",
    "ar-SA": "تتضمن هذه الفئة المركبات ذات الميزات المخصصة لذوي الاحتياجات الخاصة.",
    "hi-IN": "इस श्रेणी में पहुंच-क्षमता सुविधाओं वाले वाहन शामिल हैं।",
    "ko-KR": "이 카테고리에는 접근성 기능이 있는 차량이 포함됩니다.",
    "he-IL": "קטגוריה זו כוללת כלי רכב עם תכונות נגישות.",
    "uk-UA": "Ця категорія включає транспортні засоби з функціями доступності.",
    "id-ID": "Kategori ini mencakup kendaraan dengan fitur aksesibilitas.",
    "th-TH": "หมวดหมู่นี้รวมถึงยานพาหนะที่มีคุณสมบัติการเข้าถึงสำหรับผู้พิการ"
  },
  "Category_accessible_desc": {
    "pt-PT": "Esta categoria inclui veículos com funcionalidades de acessibilidade.",
    "pt-BR": "Esta categoria inclui veículos com recursos de acessibilidade.",
    "en-US": "This category includes vehicles with accessibility features.",
    "es-ES": "Esta categoría incluye vehículos con características de accesibilidad.",
    "fr-FR": "Cette catégorie inclut les véhicules avec des fonctionnalités d'accessibilité.",
    "de-DE": "Diese Kategorie umfasst Fahrzeuge mit Barrierefreiheitsfunktionen.",
    "it-IT": "Questa categoria include veicoli con funzionalità di accessibilità.",
    "ja-JP": "このカテゴリーには、バリアフリー機能を持つ車両が含まれます。",
    "zh-CN": "此类车辆具备无障碍功能。",
    "ru-RU": "В эту категорию входят транспортные средства с функциями доступности.",
    "ar-SA": "تتضمن هذه الفئة المركبات ذات الميزات المخصصة لذوي الاحتياجات الخاصة.",
    "hi-IN": "इस श्रेणी में पहुंच-क्षमता सुविधाओं वाले वाहन शामिल हैं।",
    "ko-KR": "이 카테고리에는 접근성 기능이 있는 차량이 포함됩니다.",
    "he-IL": "קטגוריה זו כוללת כלי רכב עם תכונות נגישות.",
    "uk-UA": "Ця категорія включає транспортні засоби з функціями доступності.",
    "id-ID": "Kategori ini mencakup kendaraan dengan fitur aksesibilitas.",
    "th-TH": "หมวดหมู่นี้รวมถึงยานพาหนะที่มีคุณสมบัติการเข้าถึงสำหรับผู้พิการ"
  },
  "btn_passenger_title": {
    "pt-PT": "Passageiro",
    "pt-BR": "Passageiro",
    "en-US": "Passenger",
    "es-ES": "Pasajero",
    "fr-FR": "Passager",
    "de-DE": "Passagier",
    "it-IT": "Passeggero",
    "ja-JP": "乗客",
    "zh-CN": "乘客",
    "ru-RU": "Пассажир",
    "ar-SA": "راكب",
    "hi-IN": "यात्री",
    "ko-KR": "승객",
    "he-IL": "נוסע",
    "uk-UA": "Пасажир",
    "id-ID": "Penumpang",
    "th-TH": "ผู้โดยสาร"
  },
  "welcome_title_p1": {
    "pt-PT": "Taxi ",
    "pt-BR": "Taxi ",
    "en-US": "Taxi ",
    "es-ES": "Taxi ",
    "fr-FR": "Taxi ",
    "de-DE": "Taxi ",
    "it-IT": "Taxi ",
    "ja-JP": "Taxi",
    "zh-CN": "Taxi",
    "ru-RU": "Taxi",
    "ar-SA": "Taxi",
    "hi-IN": "Taxi",
    "ko-KR": "Taxi",
    "he-IL":  "Taxi",
    "uk-UA": "ЗTaxi",
    "id-ID": "Taxi",
    "th-TH": "Taxi"
  },
  "soul_title": {
    "pt-PT": "A nossa alma",
    "pt-BR": "Nossa alma",
    "en-US": "Our soul",
    "es-ES": "Nuestra alma",
    "fr-FR": "Notre âme",
    "de-DE": "Unsere Seele",
    "it-IT": "La nostra anima",
    "ja-JP": "私たちの魂",
    "zh-CN": "我们的灵魂",
    "ru-RU": "Наша душа",
    "ar-SA": "روحنا",
    "hi-IN": "हमारी आत्मा",
    "ko-KR": "우리의 영혼",
    "he-IL": "הנשמה שלנו",
    "uk-UA": "Наша душа",
    "id-ID": "Jiwa kami",
    "th-TH": "จิตวิญญาณของเรา"
  },
  "soul_subtitle": {
    "pt-PT": "Pessoas à frente da tecnologia, com a missão de fazer o bem.",
    "pt-BR": "Pessoas à frente da tecnologia, com a missão de fazer o bem.",
    "en-US": "People before technology, with a mission to do good.",
    "es-ES": "Personas antes que tecnología, con la misión de hacer el bien.",
    "fr-FR": "Les gens avant la technologie, avec pour mission de faire le bien.",
    "de-DE": "Menschen vor Technologie, mit der Mission, Gutes zu tun.",
    "it-IT": "Le persone prima della tecnologia, con la missione di fare del bene.",
    "ja-JP": "テクノロジーよりも人を大切にし、善を行うことを使命とします。",
    "zh-CN": "以人为本，以行善为使命。",
    "ru-RU": "Люди важнее технологий, с миссией творить добро.",
    "ar-SA": "الناس قبل التكنولوجيا، بمهمة فعل الخير.",
    "hi-IN": "प्रौद्योगिकी से पहले लोग, अच्छा करने के मिशन के साथ।",
    "ko-KR": "기술보다 사람을 먼저 생각하며, 선을 행하는 사명감을 가지고 있습니다.",
    "he-IL": "אנשים לפני טכנולוגיה, עם שליחות לעשות טוב.",
    "uk-UA": "Люди важливіші за технології, з місією творити добро.",
    "id-ID": "Manusia di atas teknologi, dengan misi untuk berbuat baik.",
    "th-TH": "คนสำคัญกว่าเทคโนโลยี ด้วยภารกิจที่จะทำความดี"
  },
  "virtual_queue_title": {
    "pt-PT": "Fila Virtual",
    "pt-BR": "Fila Virtual",
    "en-US": "Virtual Queue",
    "es-ES": "Cola virtual",
    "fr-FR": "File d'attente virtuelle",
    "de-DE": "Virtuelle Warteschlange",
    "it-IT": "Coda virtuale",
    "ja-JP": "仮想キュー",
    "zh-CN": "虚拟队列",
    "ru-RU": "Виртуальная очередь",
    "ar-SA": "قائمة الانتظار الافتراضية",
    "hi-IN": "वर्चुअल कतार",
    "ko-KR": "가상 대기열",
    "he-IL": "תור וירטואלי",
    "uk-UA": "Віртуальна черга",
    "id-ID": "Antrean virtual",
    "th-TH": "คิวเสมือนจริง"
  },
  "virtual_queue_desc": {
    "pt-PT": "Receba corridas com base na sua localização na fila, a mais justa da sua cidade.",
    "pt-BR": "Receba corridas com base na sua localização na fila, a mais justa da sua cidade.",
    "en-US": "Receive rides based on your position in the queue, the fairest in your city.",
    "es-ES": "Recibe viajes según tu posición en la cola, la más justa de tu ciudad.",
    "fr-FR": "Recevez des courses en fonction de votre position dans la file d'attente, la plus équitable de votre ville.",
    "de-DE": "Erhalten Sie Fahrten basierend auf Ihrer Position in der Warteschlange, der fairsten in Ihrer Stadt.",
    "it-IT": "Ricevi corse in base alla tua posizione in coda, la più equa della tua città.",
    "ja-JP": "あなたの街で最も公平な、キューでのあなたの位置に基づいて配車を受け取ります。",
    "zh-CN": "根据您在队列中的位置接收行程，这是您所在城市最公平的方式。",
    "ru-RU": "Получайте поездки в зависимости от вашей позиции в очереди, самой справедливой в вашем городе.",
    "ar-SA": "احصل على الرحلات بناءً على موقعك في قائمة الانتظار، الأكثر عدالة في مدينتك.",
    "hi-IN": "अपने शहर में सबसे निष्पक्ष, कतार में अपनी स्थिति के आधार पर राइड प्राप्त करें।",
    "ko-KR": "도시에서 가장 공정한, 대기열에서의 위치에 따라 탑승을 받으세요.",
    "he-IL": "קבל נסיעות על בסיס המיקום שלך בתור, שהיא ההוגנת ביותר בעיר שלך.",
    "uk-UA": "Отримуйте поїздки на основі вашої позиції в черзі, що є найсправедливішою у вашому місті.",
    "id-ID": "Terima tumpangan berdasarkan posisi Anda dalam antrean, yang paling adil di kota Anda.",
    "th-TH": "รับงานตามตำแหน่งของคุณในคิว ซึ่งเป็นวิธีที่ยุติธรรมที่สุดในเมืองของคุณ"
  },
  "direct_payment_title": {
    "pt-PT": "Pagamento Direto",
    "pt-BR": "Pagamento Direto",
    "en-US": "Direct Payment",
    "es-ES": "Pago directo",
    "fr-FR": "Paiement direct",
    "de-DE": "Direktzahlung",
    "it-IT": "Pagamento diretto",
    "ja-JP": "直接支払い",
    "zh-CN": "直接付款",
    "ru-RU": "Прямая оплата",
    "ar-SA": "الدفع المباشر",
    "hi-IN": "सीधा भुगतान",
    "ko-KR": "직접 결제",
    "he-IL": "תשלום ישיר",
    "uk-UA": "Пряма оплата",
    "id-ID": "Pembayaran langsung",
    "th-TH": "การชำระเงินโดยตรง"
  },
  "direct_payment_desc": {
    "pt-PT": "Receba o valor das corridas diretamente na sua conta, sem intermediários.",
    "pt-BR": "Receba o valor das corridas diretamente na sua conta, sem intermediários.",
    "en-US": "Receive ride fees directly into your account, with no intermediaries.",
    "es-ES": "Recibe las tarifas de los viajes directamente en tu cuenta, sin intermediarios.",
    "fr-FR": "Recevez les frais de course directement sur votre compte, sans intermédiaires.",
    "de-DE": "Erhalten Sie die Fahrtkosten direkt auf Ihr Konto, ohne Zwischenhändler.",
    "it-IT": "Ricevi le tariffe delle corse direttamente sul tuo conto, senza intermediari.",
    "ja-JP": "仲介業者なしで、乗車料金をアカウントに直接受け取ります。",
    "zh-CN": "车费直接存入您的账户，没有中间人。",
    "ru-RU": "Получайте плату за поездки напрямую на свой счет, без посредников.",
    "ar-SA": "احصل على رسوم الرحلات مباشرة في حسابك، بدون وسطاء.",
    "hi-IN": "बिना किसी मध्यस्थ के, सीधे अपने खाते में राइड शुल्क प्राप्त करें।",
    "ko-KR": "중개인 없이 라이드 요금을 계정으로 직접 받으세요.",
    "he-IL": "קבל את דמי הנסיעה ישירות לחשבון שלך, ללא מתווכים.",
    "uk-UA": "Отримуйте плату за поїздки безпосередньо на свій рахунок, без посередників.",
    "id-ID": "Terima biaya perjalanan langsung ke akun Anda, tanpa perantara.",
    "th-TH": "รับค่าธรรมเนียมการเดินทางเข้าบัญชีของคุณโดยตรง โดยไม่มีคนกลาง"
  },
  "welcome_title_p2": {
    "pt-PT": "Inteligente",
    "pt-BR": "Inteligente",
    "en-US": "Inteligente",
    "es-ES": "Inteligente",
    "fr-FR": "Inteligente",
    "de-DE": "Inteligente",
    "it-IT": "Inteligente",
    "ja-JP": "Inteligente",
    "zh-CN": "Inteligente",
    "ru-RU": "Inteligente",
    "ar-SA": "Inteligente",
    "hi-IN": "Inteligente",
    "ko-KR": "Inteligente",
    "he-IL": "Inteligente",
    "uk-UA": "Inteligente",
    "id-ID": "Inteligente",
    "th-TH": "Inteligente"
  },
  "btn_driver_mototaxi_title": {
    "pt-PT": "Motorista / MotoTáxi",
    "pt-BR": "Motorista / MotoTáxi",
    "en-US": "MotoTaxi / Driver",
    "es-ES": "Conductor / mototaxi",
    "fr-FR": "Chauffeur / mototaxi",
    "de-DE": "Motorrad-/Taxifahrer",
    "it-IT": "Autista / mototaxi",
    "ja-JP": "バイク/タクシー運転手",
    "zh-CN": "摩托车/出租车司机",
    "ru-RU": "Водитель мотоцикла/такси",
    "ar-SA": "سائق دراجة نارية/أجرة",
    "hi-IN": "मोटरसाइकिल/टैक्सी ड्राइवर",
    "ko-KR": "오토바이/택시 운전사",
    "he-IL": "נהג אופנוע/מונית",
    "uk-UA": "Водій мотоцикла/таксі",
    "id-ID": "Pengemudi Sepeda Motor/Taksi",
    "th-TH": "คนขับรถมอเตอร์ไซค์/แท็กซี่"
  },
  "auth_dialog_title_login": {
    "pt-PT": "Iniciar Sessão",
    "pt-BR": "Fazer Login",
    "en-US": "Log In",
    "es-ES": "Iniciar sesión",
    "fr-FR": "Se connecter",
    "de-DE": "Anmelden",
    "it-IT": "Accedi",
    "ja-JP": "ログイン",
    "zh-CN": "登录",
    "ru-RU": "Войти",
    "ar-SA": "تسجيل الدخول",
    "hi-IN": "लॉग इन करें",
    "ko-KR": "로그인",
    "he-IL": "התחבר",
    "uk-UA": "Увійти",
    "id-ID": "Masuk",
    "th-TH": "เข้าสู่ระบบ"
  },
  "auth_dialog_desc_login": {
    "pt-PT": "Insira as suas credenciais para aceder ao painel de passageiro.",
    "pt-BR": "Insira suas credenciais para acessar o painel de passageiro.",
    "en-US": "Enter your credentials to access the passenger dashboard.",
    "es-ES": "Introduce tus credenciales para acceder al panel de pasajero.",
    "fr-FR": "Entrez vos identifiants pour accéder au tableau de bord passager.",
    "de-DE": "Geben Sie Ihre Anmeldedaten ein, um auf das Passagier-Dashboard zuzugreifen.",
    "it-IT": "Inserisci le tue credenziali per accedere al pannello passeggero.",
    "ja-JP": "乗客ダッシュボードにアクセスするには、資格情報を入力してください。",
    "zh-CN": "输入您的凭据以访问乘客仪表板。",
    "ru-RU": "Введите свои учетные данные, чтобы получить доступ к панели пассажира.",
    "ar-SA": "أدخل بيانات الاعتماد الخاصة بك للوصول إلى لوحة تحكم الراكب.",
    "hi-IN": "यात्री डैशबोर्ड तक पहुंचने के लिए अपनी साख दर्ज करें।",
    "ko-KR": "승객 대시보드에 액세스하려면 자격 증명을 입력하세요.",
    "he-IL": "הזן את פרטי ההתחברות שלך כדי לגשת ללוח המחוונים של הנוסע.",
    "uk-UA": "Введіть свої облікові дані, щоб отримати доступ до панелі пасажира.",
    "id-ID": "Masukkan kredensial Anda untuk mengakses dasbor penumpang.",
    "th-TH": "ป้อนข้อมูลประจำตัวของคุณเพื่อเข้าถึงแดชบอร์ดของผู้โดยสาร"
  },
  "email_label": {
    "pt-PT": "E-mail",
    "pt-BR": "E-mail",
    "en-US": "Email",
    "es-ES": "Correo electrónico",
    "fr-FR": "E-mail",
    "de-DE": "E-Mail",
    "it-IT": "E-mail",
    "ja-JP": "メール",
    "zh-CN": "电子邮件",
    "ru-RU": "Электронная почта",
    "ar-SA": "بريد إلكتروني",
    "hi-IN": "ईमेल",
    "ko-KR": "이메일",
    "he-IL": "דוא\"ל",
    "uk-UA": "Електронна пошта",
    "id-ID": "Email",
    "th-TH": "อีเมล"
  },
  "password_label": {
    "pt-PT": "Palavra-passe",
    "pt-BR": "Senha",
    "en-US": "Password",
    "es-ES": "Contraseña",
    "fr-FR": "Mot de passe",
    "de-DE": "Passwort",
    "it-IT": "Password",
    "ja-JP": "パスワード",
    "zh-CN": "密码",
    "ru-RU": "Пароль",
    "ar-SA": "كلمة المرور",
    "hi-IN": "पासवर्ड",
    "ko-KR": "비밀번호",
    "he-IL": "סיסמה",
    "uk-UA": "Пароль",
    "id-ID": "Kata sandi",
    "th-TH": "รหัสผ่าน"
  },
  "specialized_services_title": {
    "pt-PT": "Serviços Especializados",
    "pt-BR": "Serviços Especializados",
    "en-US": "Specialized Services",
    "es-ES": "Servicios especializados",
    "fr-FR": "Services spécialisés",
    "de-DE": "Spezialisierte Dienstleistungen",
    "it-IT": "Servizi specializzati",
    "ja-JP": "専門サービス",
    "zh-CN": "专业服务",
    "ru-RU": "Специализированные услуги",
    "ar-SA": "خدمات متخصصة",
    "hi-IN": "विशेषज्ञ सेवाएं",
    "ko-KR": "전문 서비스",
    "he-IL": "שירותים מיוחדים",
    "uk-UA": "Спеціалізовані послуги",
    "id-ID": "Layanan khusus",
    "th-TH": "บริการเฉพาะทาง"
  },
  "specialized_services_desc": {
    "pt-PT": "A nossa plataforma oferece diferentes tipos de serviço para além das viagens de passageiros e entregas.",
    "pt-BR": "Nossa plataforma oferece diferentes tipos de serviço além das viagens de passageiros e entregas.",
    "en-US": "Our platform offers different types of service beyond passenger trips and deliveries.",
    "es-ES": "Nuestra plataforma ofrece diferentes tipos de servicio además de los viajes de pasajeros y las entregas.",
    "fr-FR": "Notre plateforme propose différents types de services au-delà des trajets de passagers et des livraisons.",
    "de-DE": "Unsere Plattform bietet verschiedene Arten von Dienstleistungen jenseits von Passagierfahrten und Lieferungen.",
    "it-IT": "La nostra piattaforma offre diversi tipi di servizi oltre ai viaggi passeggeri e alle consegne.",
    "ja-JP": "当社のプラットフォームは、乗客の旅や配達以外にも、さまざまな種類のサービスを提供しています。",
    "zh-CN": "我们的平台除了乘客出行和送货之外，还提供不同类型的服务。",
    "ru-RU": "Наша платформа предлагает различные виды услуг, помимо пассажирских перевозок и доставки.",
    "ar-SA": "منصتنا تقدم أنواعاً مختلفة من الخدمات بالإضافة إلى رحلات الركاب والتوصيل.",
    "hi-IN": "हमारा प्लेटफॉर्म यात्री यात्रा और डिलीवरी के अलावा विभिन्न प्रकार की सेवाएं प्रदान करता है।",
    "ko-KR": "저희 플랫폼은 승객 여행 및 배송 외에도 다양한 종류의 서비스를 제공합니다.",
    "he-IL": "הפלטפורמה שלנו מציעה סוגי שירות שונים מעבר לנסיעות נוסעים ומשלוחים.",
    "uk-UA": "Наша платформа пропонує різні види послуг, окрім пасажирських поїздок та доставок.",
    "id-ID": "Platform kami menawarkan berbagai jenis layanan di luar perjalanan penumpang dan pengiriman.",
    "th-TH": "แพลตฟอร์มของเราให้บริการที่หลากหลาย นอกเหนือจากการเดินทางของผู้โดยสารและการจัดส่ง"
  },
  "service_freight_title": {
    "pt-PT": "Transporte de Cargas",
    "pt-BR": "Transporte de Cargas",
    "en-US": "Freight Transport",
    "es-ES": "Transporte de carga",
    "fr-FR": "Transport de marchandises",
    "de-DE": "Gütertransport",
    "it-IT": "Trasporto merci",
    "ja-JP": "貨物輸送",
    "zh-CN": "货运",
    "ru-RU": "Грузоперевозки",
    "ar-SA": "نقل البضائع",
    "hi-IN": "माल ढुलाई परिवहन",
    "ko-KR": "화물 운송",
    "he-IL": "הובלת מטענים",
    "uk-UA": "Вантажні перевезення",
    "id-ID": "Angkutan barang",
    "th-TH": "การขนส่งสินค้า"
  },
  "service_freight_desc": {
    "pt-PT": "Serviço dedicado para o transporte de cargas e volumes maiores.",
    "pt-BR": "Serviço dedicado para o transporte de cargas e volumes maiores.",
    "en-US": "Dedicated service for the transport of larger loads and volumes.",
    "es-ES": "Servicio dedicado para el transporte de cargas y volúmenes más grandes.",
    "fr-FR": "Service dédié au transport de charges et de volumes plus importants.",
    "de-DE": "Spezialisierter Service für den Transport von größeren Lasten und Volumen.",
    "it-IT": "Servizio dedicato per il trasporto di carichi e volumi più grandi.",
    "ja-JP": "より大きな荷物や容積の輸送に特化したサービス。",
    "zh-CN": "专为运输更大的货物和体积而设的服务。",
    "ru-RU": "Специализированная услуга по перевозке более крупных грузов и объемов.",
    "ar-SA": "خدمة مخصصة لنقل الأحمال والأحجام الكبيرة.",
    "hi-IN": "बड़े भार और मात्रा के परिवहन के लिए समर्पित सेवा।",
    "ko-KR": "더 큰 화물과 부피를 운송하기 위한 전용 서비스입니다.",
    "he-IL": "שירות ייעודי להובלת מטענים ונפחים גדולים יותר.",
    "uk-UA": "Спеціалізована послуга для перевезення великих вантажів та об'ємів.",
    "id-ID": "Layanan khusus untuk pengangkutan muatan dan volume yang lebih besar.",
    "th-TH": "บริการเฉพาะสำหรับการขนส่งสินค้าขนาดใหญ่และปริมาตรที่มากกว่า"
  },
  "business_model_title": {
    "pt-PT": "Modelo de Negócio",
    "pt-BR": "Modelo de Negócio",
    "en-US": "Business Model",
    "es-ES": "Modelo de negocio",
    "fr-FR": "Modèle d'affaires",
    "de-DE": "Geschäftsmodell",
    "it-IT": "Modello di business",
    "ja-JP": "ビジネスモデル",
    "zh-CN": "商业模式",
    "ru-RU": "Бизнес-модель",
    "ar-SA": "نموذج العمل",
    "hi-IN": "व्यावसायिक मॉडल",
    "ko-KR": "사업 모델",
    "he-IL": "מודל עסקי",
    "uk-UA": "Бізнес-модель",
    "id-ID": "Model bisnis",
    "th-TH": "รูปแบบธุรกิจ"
  },
  "business_model_subtitle": {
    "pt-PT": "Como funcionamos?",
    "pt-BR": "Como funcionamos?",
    "en-US": "How do we work?",
    "es-ES": "¿Cómo funcionamos?",
    "fr-FR": "Comment fonctionnons-nous ?",
    "de-DE": "Wie arbeiten wir?",
    "it-IT": "Come funzioniamo?",
    "ja-JP": "どのように機能しますか？",
    "zh-CN": "我们如何运作？",
    "ru-RU": "Как мы работаем?",
    "ar-SA": "كيف نعمل؟",
    "hi-IN": "हम कैसे काम करते हैं?",
    "ko-KR": "어떻게 작동하나요?",
    "he-IL": "איך אנחנו עובדים?",
    "uk-UA": "Як ми працюємо?",
    "id-ID": "Bagaimana kami bekerja?",
    "th-TH": "เราทำงานอย่างไร?"
  },
  "business_model_flow_title": {
    "pt-PT": "A nossa parceria, passo a passo.",
    "pt-BR": "Nossa parceria, passo a passo.",
    "en-US": "Our partnership, step by step.",
    "es-ES": "Nuestra asociación, paso a paso.",
    "fr-FR": "Notre partenariat, étape par étape.",
    "de-DE": "Unsere Partnerschaft, Schritt für Schritt.",
    "it-IT": "La nostra partnership, passo dopo passo.",
    "ja-JP": "私たちのパートナーシップ、ステップバイステップ。",
    "zh-CN": "我们的合作伙伴关系，循序渐进。",
    "ru-RU": "Наше партнерство, шаг за шагом.",
    "ar-SA": "شراكتنا، خطوة بخطوة.",
    "hi-IN": "हमारी साझेदारी, चरण-दर-चरण।",
    "ko-KR": "단계별 파트너십.",
    "he-IL": "השותפות שלנו, צעד אחר צעד.",
    "uk-UA": "Наше партнерство, крок за кроком.",
    "id-ID": "Kemitraan kami, langkah demi langkah.",
    "th-TH": "พันธมิตรของเรา ทีละขั้นตอน"
  },
  "business_model_step1_title": {
    "pt-PT": "Motorista aceita a corrida",
    "pt-BR": "Motorista aceita a corrida",
    "en-US": "Driver accepts the ride",
    "es-ES": "El conductor acepta el viaje",
    "fr-FR": "Le chauffeur accepte la course",
    "de-DE": "Fahrer nimmt die Fahrt an",
    "it-IT": "L'autista accetta la corsa",
    "ja-JP": "ドライバーが乗車を承諾",
    "zh-CN": "司机接受行程",
    "ru-RU": "Водитель принимает заказ",
    "ar-SA": "السائق يقبل الرحلة",
    "hi-IN": "ड्राइवर राइड स्वीकार करता है",
    "ko-KR": "운전자가 탑승을 수락합니다",
    "he-IL": "הנהג מקבל את הנסיעה",
    "uk-UA": "Водій приймає поїздку",
    "id-ID": "Pengemudi menerima perjalanan",
    "th-TH": "คนขับรับงาน"
  },
  "business_model_step1_desc": {
    "pt-PT": "O motorista aceita uma corrida e conclui o trajeto do início ao fim.",
    "pt-BR": "O motorista aceita uma corrida e conclui o trajeto do início ao fim.",
    "en-US": "The driver accepts a ride and completes the trip from start to finish.",
    "es-ES": "El conductor acepta un viaje y lo completa de principio a fin.",
    "fr-FR": "Le chauffeur accepte une course et la termine du début à la fin.",
    "de-DE": "Der Fahrer nimmt eine Fahrt an und schließt die Fahrt von Anfang bis Ende ab.",
    "it-IT": "L'autista accetta una corsa e completa il viaggio dall'inizio alla fine.",
    "ja-JP": "ドライバーは乗車を承諾し、最初から最後まで旅を完了します。",
    "zh-CN": "司机接受行程并从头到尾完成行程。",
    "ru-RU": "Водитель принимает заказ и завершает поездку от начала до конца.",
    "ar-SA": "يقبل السائق الرحلة ويكملها من البداية إلى النهاية.",
    "hi-IN": "ड्राइवर एक राइड स्वीकार करता है और शुरू से अंत तक यात्रा पूरी करता है।",
    "ko-KR": "운전자는 탑승을 수락하고 처음부터 끝까지 여행을 완료합니다.",
    "he-IL": "הנהג מקבל נסיעה ומשלים אותה מתחילתה ועד סופה.",
    "uk-UA": "Водій приймає поїздку і завершує її від початку до кінця.",
    "id-ID": "Pengemudi menerima perjalanan dan menyelesaikannya dari awal hingga akhir.",
    "th-TH": "คนขับรับงานและดำเนินการจนเสร็จสิ้นตั้งแต่ต้นจนจบ"
  },
  "business_model_step2_title": {
    "pt-PT": "Plataforma processa a transação",
    "pt-BR": "Plataforma processa a transação",
    "en-US": "Platform processes the transaction",
    "es-ES": "La plataforma procesa la transacción",
    "fr-FR": "La plateforme traite la transaction",
    "de-DE": "Plattform verarbeitet die Transaktion",
    "it-IT": "La piattaforma elabora la transazione",
    "ja-JP": "プラットフォームが取引を処理",
    "zh-CN": "平台处理交易",
    "ru-RU": "Платформа обрабатывает транзакцию",
    "ar-SA": "المنصة تقوم بمعالجة المعاملة",
    "hi-IN": "प्लेटफ़ॉर्म लेनदेन को संसाधित करता है",
    "ko-KR": "플랫폼이 거래를 처리합니다",
    "he-IL": "הפלטפורמה מעבדת את העסקה",
    "uk-UA": "Платформа обробляє транзакцію",
    "id-ID": "Platform memproses transaksi",
    "th-TH": "แพลตฟอร์มประมวลผลการทำธุรกรรม"
  },
  "business_model_step2_desc": {
    "pt-PT": "A plataforma cobra uma pequena taxa de comissão sobre o valor total da corrida.",
    "pt-BR": "A plataforma cobra uma pequena taxa de comissão sobre o valor total da corrida.",
    "en-US": "The platform charges a small commission fee on the total ride fare.",
    "es-ES": "La plataforma cobra una pequeña comisión sobre el valor total del viaje.",
    "fr-FR": "La plateforme prélève une petite commission sur le montant total de la course.",
    "de-DE": "Die Plattform erhebt eine kleine Provision auf den gesamten Fahrpreis.",
    "it-IT": "La piattaforma applica una piccola commissione sul costo totale della corsa.",
    "ja-JP": "プラットフォームは、乗車料金の合計から少額の手数料を請求します。",
    "zh-CN": "平台对总行程费用收取少量佣金。",
    "ru-RU": "Платформа взимает небольшую комиссию от общей стоимости поездки.",
    "ar-SA": "تتقاضى المنصة رسوم عمولة بسيطة على إجمالي أجرة الرحلة.",
    "hi-IN": "प्लेटफ़ॉर्म कुल राइड किराए पर एक छोटा कमीशन शुल्क लेता है।",
    "ko-KR": "플랫폼은 총 탑승 요금에 대해 소액의 수수료를 부과합니다.",
    "he-IL": "הפלטפורמה גובה עמלה קטנה על סך תעריף הנסיעה.",
    "uk-UA": "Платформа стягує невелику комісію з загальної вартості поїздки.",
    "id-ID": "Platform mengenakan biaya komisi kecil dari total ongkos perjalanan.",
    "th-TH": "แพลตฟอร์มจะเรียกเก็บค่าคอมมิชชั่นเล็กน้อยจากค่าโดยสารทั้งหมด"
  },
  "business_model_step3_title": {
    "pt-PT": "Pagamento imediato ao motorista",
    "pt-BR": "Pagamento imediato ao motorista",
    "en-US": "Immediate payment to the driver",
    "es-ES": "Pago inmediato al conductor",
    "fr-FR": "Paiement immédiat au chauffeur",
    "de-DE": "Sofortige Zahlung an den Fahrer",
    "it-IT": "Pagamento immediato all'autista",
    "ja-JP": "ドライバーへの即時支払い",
    "zh-CN": "立即向司机付款",
    "ru-RU": "Мгновенная оплата водителю",
    "ar-SA": "دفع فوري للسائق",
    "hi-IN": "ड्राइवर को तत्काल भुगतान",
    "ko-KR": "운전자에게 즉시 결제",
    "he-IL": "תשלום מיידי לנהג",
    "uk-UA": "Миттєва оплата водію",
    "id-ID": "Pembayaran langsung kepada pengemudi",
    "th-TH": "ชำระเงินให้คนขับทันที"
  },
  "business_model_step3_desc": {
    "pt-PT": "O valor restante da corrida é transferido imediatamente para a conta do motorista.",
    "pt-BR": "O valor restante da corrida é transferido imediatamente para a conta do motorista.",
    "en-US": "The remaining ride amount is transferred immediately to the driver's account.",
    "es-ES": "El importe restante del viaje se transfiere inmediatamente a la cuenta del conductor.",
    "fr-FR": "Le montant restant de la course est transféré immédiatement sur le compte du chauffeur.",
    "de-DE": "Der verbleibende Fahrbetrag wird sofort auf das Konto des Fahrers überwiesen.",
    "it-IT": "L'importo restante della corsa viene trasferito immediatamente sull'account dell'autista.",
    "ja-JP": "残りの乗車料金は、ドライバーのアカウントに即座に送金されます。",
    "zh-CN": "剩余的行程费用将立即转入司机的账户。",
    "ru-RU": "Оставшаяся сумма за поездку немедленно переводится на счет водителя.",
    "ar-SA": "يتم تحويل المبلغ المتبقي من الرحلة فورًا إلى حساب السائق.",
    "hi-IN": "शेष राइड राशि तुरंत ड्राइवर के खाते में स्थानांतरित कर दी जाती है।",
    "ko-KR": "남은 탑승 금액은 즉시 운전자의 계정으로 이체됩니다.",
    "he-IL": "יתרת סכום הנסיעה מועברת מיד לחשבון הנהג.",
    "uk-UA": "Залишок суми за поїздку негайно перераховується на рахунок водія.",
    "id-ID": "Sisa biaya perjalanan segera ditransfer ke akun pengemudi.",
    "th-TH": "จำนวนเงินที่เหลือจากการเดินทางจะถูกโอนเข้าบัญชีคนขับทันที"
  },
  "footer_terms": {
    "pt-PT": "Termos de Serviço",
    "pt-BR": "Termos de Serviço",
    "en-US": "Terms of Service",
    "es-ES": "Términos de Servicio",
    "fr-FR": "Conditions d'utilisation",
    "de-DE": "Nutzungsbedingungen",
    "it-IT": "Termini di servizio",
    "ja-JP": "利用規約",
    "zh-CN": "服务条款",
    "ru-RU": "Условия использования",
    "ar-SA": "شروط الخدمة",
    "hi-IN": "सेवा की शर्तें",
    "ko-KR": "서비스 약관",
    "he-IL": "תנאי שירות",
    "uk-UA": "Умови використання",
    "id-ID": "Ketentuan Layanan",
    "th-TH": "ข้อกำหนดในการให้บริการ"
  },
  "footer_privacy": {
    "pt-PT": "Política de Privacidade",
    "pt-BR": "Política de Privacidade",
    "en-US": "Privacy Policy",
    "es-ES": "Política de Privacidad",
    "fr-FR": "Politique de confidentialité",
    "de-DE": "Datenschutzbestimmungen",
    "it-IT": "Informativa sulla privacy",
    "ja-JP": "プライバシーポリシー",
    "zh-CN": "隐私政策",
    "ru-RU": "Политика конфиденциальности",
    "ar-SA": "سياسة الخصوصية",
    "hi-IN": "गोपनीयता नीति",
    "ko-KR": "개인정보처리방침",
    "he-IL": "מדיניות פרטיות",
    "uk-UA": "Політика конфіденційності",
    "id-ID": "Kebijakan Privasi",
    "th-TH": "นโยบายความเป็นส่วนตัว"
  },
  "footer_contact": {
    "pt-PT": "Contacto",
    "pt-BR": "Contato",
    "en-US": "Contact",
    "es-ES": "Contacto",
    "fr-FR": "Contact",
    "de-DE": "Kontakt",
    "it-IT": "Contatti",
    "ja-JP": "お問い合わせ",
    "zh-CN": "联系方式",
    "ru-RU": "Контакты",
    "ar-SA": "اتصل بنا",
    "hi-IN": "संपर्क करें",
    "ko-KR": "연락처",
    "he-IL": "צור קשר",
    "uk-UA": "Контакти",
    "id-ID": "Kontak",
    "th-TH": "ติดต่อ"
  },
  "menu_wallet": {
    "pt-PT": "Carteira",
    "pt-BR": "Carteira",
    "en-US": "Wallet",
    "es-ES": "Billetera",
    "fr-FR": "Portefeuille",
    "de-DE": "Brieftasche",
    "it-IT": "Portafoglio",
    "ja-JP": "ウォレット",
    "zh-CN": "钱包",
    "ru-RU": "Кошелек",
    "ar-SA": "المحفظة",
    "hi-IN": "वॉलेट",
    "ko-KR": "지갑",
    "he-IL": "ארנק",
    "uk-UA": "Гаманець",
    "id-ID": "Dompet",
    "th-TH": "กระเป๋าเงิน"
  },
  "menu_billing": {
    "pt-PT": "Faturação",
    "pt-BR": "Faturamento",
    "en-US": "Billing",
    "es-ES": "Facturación",
    "fr-FR": "Facturation",
    "de-DE": "Abrechnung",
    "it-IT": "Fatturazione",
    "ja-JP": "請求",
    "zh-CN": "账单",
    "ru-RU": "Счета",
    "ar-SA": "الفواتير",
    "hi-IN": "बिलिंग",
    "ko-KR": "청구",
    "he-IL": "חיוב",
    "uk-UA": "Рахунки",
    "id-ID": "Tagihan",
    "th-TH": "การเรียกเก็บเงิน"
  },
  "menu_payments": {
    "pt-PT": "Pagamentos",
    "pt-BR": "Pagamentos",
    "en-US": "Payments",
    "es-ES": "Pagos",
    "fr-FR": "Paiements",
    "de-DE": "Zahlungen",
    "it-IT": "Pagamenti",
    "ja-JP": "支払い",
    "zh-CN": "付款",
    "ru-RU": "Платежи",
    "ar-SA": "المدفوعات",
    "hi-IN": "भुगतान",
    "ko-KR": "결제",
    "he-IL": "תשלומים",
    "uk-UA": "Платежі",
    "id-ID": "Pembayaran",
    "th-TH": "การชำระเงิน"
  },
  "menu_chat": {
    "pt-PT": "Chat",
    "pt-BR": "Chat",
    "en-US": "Chat",
    "es-ES": "Chat",
    "fr-FR": "Chat",
    "de-DE": "Chat",
    "it-IT": "Chat",
    "ja-JP": "チャット",
    "zh-CN": "聊天",
    "ru-RU": "Чат",
    "ar-SA": "المحادثة",
    "hi-IN": "चैट",
    "ko-KR": "채팅",
    "he-IL": "צ'אט",
    "uk-UA": "Чат",
    "id-ID": "Obrolan",
    "th-TH": "แชท"
  },
  "menu_notifications": {
    "pt-PT": "Notificações",
    "pt-BR": "Notificações",
    "en-US": "Notifications",
    "es-ES": "Notificaciones",
    "fr-FR": "Notifications",
    "de-DE": "Benachrichtigungen",
    "it-IT": "Notifiche",
    "ja-JP": "通知",
    "zh-CN": "通知",
    "ru-RU": "Уведомления",
    "ar-SA": "الإشعارات",
    "hi-IN": "सूचनाएं",
    "ko-KR": "알림",
    "he-IL": "התראות",
    "uk-UA": "Сповіщення",
    "id-ID": "Notifikasi",
    "th-TH": "การแจ้งเตือน"
  },
  "menu_profile": {
    "pt-PT": "Perfil",
    "pt-BR": "Perfil",
    "en-US": "Profile",
    "es-ES": "Perfil",
    "fr-FR": "Profil",
    "de-DE": "Profil",
    "it-IT": "Profilo",
    "ja-JP": "プロフィール",
    "zh-CN": "个人资料",
    "ru-RU": "Профиль",
    "ar-SA": "الملف الشخصي",
    "hi-IN": "प्रोफ़ाइल",
    "ko-KR": "프로필",
    "he-IL": "פרופיל",
    "uk-UA": "Профіль",
    "id-ID": "Profil",
    "th-TH": "โปรไฟล์"
  },
  "menu_refer": {
    "pt-PT": "Recomendar",
    "pt-BR": "Indicar",
    "en-US": "Refer",
    "es-ES": "Recomendar",
    "fr-FR": "Parrainer",
    "de-DE": "Empfehlen",
    "it-IT": "Invita",
    "ja-JP": "紹介",
    "zh-CN": "推荐",
    "ru-RU": "Пригласить",
    "ar-SA": "إحالة",
    "hi-IN": "रेफर करें",
    "ko-KR": "추천",
    "he-IL": "הפנה",
    "uk-UA": "Запросити",
    "id-ID": "Ajak teman",
    "th-TH": "แนะนำ"
  },
  "menu_settings": {
    "pt-PT": "Configurações",
    "pt-BR": "Configurações",
    "en-US": "Settings",
    "es-ES": "Ajustes",
    "fr-FR": "Paramètres",
    "de-DE": "Einstellungen",
    "it-IT": "Impostazioni",
    "ja-JP": "設定",
    "zh-CN": "设置",
    "ru-RU": "Настройки",
    "ar-SA": "الإعدادات",
    "hi-IN": "सेटिंग्स",
    "ko-KR": "설정",
    "he-IL": "הגדרות",
    "uk-UA": "Налаштування",
    "id-ID": "Pengaturan",
    "th-TH": "การตั้งค่า"
  },
  "menu_support": {
    "pt-PT": "Suporte",
    "pt-BR": "Suporte",
    "en-US": "Support",
    "es-ES": "Soporte",
    "fr-FR": "Assistance",
    "de-DE": "Support",
    "it-IT": "Supporto",
    "ja-JP": "サポート",
    "zh-CN": "支持",
    "ru-RU": "Поддержка",
    "ar-SA": "الدعم",
    "hi-IN": "सहायता",
    "ko-KR": "지원",
    "he-IL": "תמיכה",
    "uk-UA": "Підтримка",
    "id-ID": "Dukungan",
    "th-TH": "สนับสนุน"
  },
  "logout": {
    "pt-PT": "Sair",
    "pt-BR": "Sair",
    "en-US": "Logout",
    "es-ES": "Cerrar sesión",
    "fr-FR": "Déconnexion",
    "de-DE": "Abmelden",
    "it-IT": "Esci",
    "ja-JP": "ログアウト",
    "zh-CN": "退出登录",
    "ru-RU": "Выйти",
    "ar-SA": "تسجيل الخروج",
    "hi-IN": "लॉग आउट",
    "ko-KR": "로그아웃",
    "he-IL": "התנתק",
    "uk-UA": "Вийти",
    "id-ID": "Keluar",
    "th-TH": "ออกจากระบบ"
  },
  "passenger_panel_welcome_title": {
    "pt-PT": "Olá, %{name}!",
    "pt-BR": "Olá, %{name}!",
    "en-US": "Hello, %{name}!",
    "es-ES": "¡Hola, %{name}!",
    "fr-FR": "Bonjour, %{name}!",
    "de-DE": "Hallo, %{name}!",
    "it-IT": "Ciao, %{name}!",
    "ja-JP": "こんにちは、%{name}さん！",
    "zh-CN": "您好, %{name}！",
    "ru-RU": "Здравствуйте, %{name}!",
    "ar-SA": "أهلاً، %{name}!",
    "hi-IN": "नमस्ते, %{name}!",
    "ko-KR": "안녕하세요, %{name}님!",
    "he-IL": "שלום, %{name}!",
    "uk-UA": "Привіт, %{name}!",
    "id-ID": "Halo, %{name}!",
    "th-TH": "สวัสดี, %{name}!"
  },
  "menu_transport": {
    "pt-PT": "Transporte",
    "pt-BR": "Transporte",
    "en-US": "Transport",
    "es-ES": "Transporte",
    "fr-FR": "Transport",
    "de-DE": "Transport",
    "it-IT": "Trasporto",
    "ja-JP": "交通機関",
    "zh-CN": "交通",
    "ru-RU": "Транспорт",
    "ar-SA": "نقل",
    "hi-IN": "परिवहन",
    "ko-KR": "교통",
    "he-IL": "תחבורה",
    "uk-UA": "Транспорт",
    "id-ID": "Transportasi",
    "th-TH": "การขนส่ง"
  },
  "menu_mototaxi": {
    "pt-PT": "Moto Táxi",
    "pt-BR": "Moto Táxi",
    "en-US": "Moto Taxi",
    "es-ES": "Moto Taxi",
    "fr-FR": "Moto Taxi",
    "de-DE": "Moto-Taxi",
    "it-IT": "Moto Taxi",
    "ja-JP": "モトタクシー",
    "zh-CN": "摩托出租车",
    "ru-RU": "Мото такси",
    "ar-SA": "تاكسي دراجة نارية",
    "hi-IN": "मोटो टैक्सी",
    "ko-KR": "오토바이 택시",
    "he-IL": "מוטו טקסי",
    "uk-UA": "Мото таксі",
    "id-ID": "Ojek",
    "th-TH": "มอเตอร์ไซค์รับจ้าง"
  },
  "menu_delivery": {
    "pt-PT": "Entregas",
    "pt-BR": "Entregas",
    "en-US": "Deliveries",
    "es-ES": "Entregas",
    "fr-FR": "Livraisons",
    "de-DE": "Lieferungen",
    "it-IT": "Consegne",
    "ja-JP": "配達",
    "zh-CN": "配送",
    "ru-RU": "Доставка",
    "ar-SA": "خدمة التوصيل",
    "hi-IN": "डिलीवरी",
    "ko-KR": "배달",
    "he-IL": "משלוחים",
    "uk-UA": "Доставки",
    "id-ID": "Pengiriman",
    "th-TH": "การจัดส่ง"
  },
  "passenger_panel_welcome_subtitle": {
    "pt-PT": "O que gostaria de fazer hoje?",
    "pt-BR": "O que você gostaria de fazer hoje?",
    "en-US": "What would you like to do today?",
    "es-ES": "¿Qué te gustaría hacer hoy?",
    "fr-FR": "Que souhaitez-vous faire aujourd'hui ?",
    "de-DE": "Was möchten Sie heute tun?",
    "it-IT": "Cosa vorresti fare oggi?",
    "ja-JP": "今日は何をしたいですか？",
    "zh-CN": "今天想做什么？",
    "ru-RU": "Что бы вы хотели сделать сегодня?",
    "ar-SA": "ماذا تريد أن تفعل اليوم؟",
    "hi-IN": "आप आज क्या करना चाहेंगे?",
    "ko-KR": "오늘 무엇을 하고 싶으신가요?",
    "he-IL": "מה תרצה לעשות היום?",
    "uk-UA": "Що б ви хотіли зробити сьогодні?",
    "id-ID": "Apa yang ingin Anda lakukan hari ini?",
    "th-TH": "วันนี้คุณต้องการทำอะไร?"
  },
  "menu_request_transport": {
    "pt-PT": "Solicitar transporte",
    "pt-BR": "Solicitar transporte",
    "en-US": "Request transport",
    "es-ES": "Solicitar transporte",
    "fr-FR": "Demander un transport",
    "de-DE": "Transport anfordern",
    "it-IT": "Richiedi trasporto",
    "ja-JP": "交通機関をリクエスト",
    "zh-CN": "请求交通",
    "ru-RU": "Запросить транспорт",
    "ar-SA": "اطلب وسيلة نقل",
    "hi-IN": "परिवहन का अनुरोध करें",
    "ko-KR": "교통편 요청",
    "he-IL": "בקש תחבורה",
    "uk-UA": "Замовити транспорт",
    "id-ID": "Minta transportasi",
    "th-TH": "ขอการเดินทาง"
  },
  "action_request_transport_desc": {
    "pt-PT": "Conecte-se com motoristas para uma viagem rápida, segura e económica.",
    "pt-BR": "Conecte-se com motoristas para uma viagem rápida, segura e econômica.",
    "en-US": "Connect with drivers for a fast, safe, and economical trip.",
    "es-ES": "Conéctate con conductores para un viaje rápido, seguro y económico.",
    "fr-FR": "Connectez-vous avec des chauffeurs pour un trajet rapide, sûr et économique.",
    "de-DE": "Verbinden Sie sich mit Fahrern für eine schnelle, sichere und wirtschaftliche Fahrt.",
    "it-IT": "Connettiti con gli autisti per un viaggio veloce, sicuro ed economico.",
    "ja-JP": "迅速、安全、経済的な旅行のためにドライバーと接続します。",
    "zh-CN": "与司机联系，享受快速、安全、经济的旅程。",
    "ru-RU": "Свяжитесь с водителями для быстрой, безопасной и экономичной поездки.",
    "ar-SA": "تواصل مع السائقين لرحلة سريعة، آمنة واقتصادية.",
    "hi-IN": "तेज़, सुरक्षित और किफायती यात्रा के लिए ड्राइवरों से जुड़ें।",
    "ko-KR": "빠르고 안전하며 경제적인 여행을 위해 운전자와 연결하세요.",
    "he-IL": "התחבר עם נהגים לנסיעה מהירה, בטוחה וחסכונית.",
    "uk-UA": "Зв'яжіться з водіями для швидкої, безпечної та економної поїздки.",
    "id-ID": "Terhubung dengan pengemudi untuk perjalanan yang cepat, aman, dan ekonomis.",
    "th-TH": "เชื่อมต่อกับคนขับสำหรับการเดินทางที่รวดเร็ว ปลอดภัย และประหยัด"
  },
  "btn_request_now": {
    "pt-PT": "Solicitar agora",
    "pt-BR": "Solicitar agora",
    "en-US": "Request now",
    "es-ES": "Solicitar ahora",
    "fr-FR": "Demander maintenant",
    "de-DE": "Jetzt anfordern",
    "it-IT": "Richiedi ora",
    "ja-JP": "今すぐリクエスト",
    "zh-CN": "立即申请",
    "ru-RU": "Запросить сейчас",
    "ar-SA": "اطلب الآن",
    "hi-IN": "अभी अनुरोध करें",
    "ko-KR": "지금 요청",
    "he-IL": "בקש עכשיו",
    "uk-UA": "Замовити зараз",
    "id-ID": "Minta sekarang",
    "th-TH": "ร้องขอตอนนี้"
  },
  "menu_request_delivery": {
    "pt-PT": "Solicitar entrega",
    "pt-BR": "Solicitar entrega",
    "en-US": "Request delivery",
    "es-ES": "Solicitar entrega",
    "fr-FR": "Demander une livraison",
    "de-DE": "Lieferung anfordern",
    "it-IT": "Richiedi consegna",
    "ja-JP": "配達をリクエスト",
    "zh-CN": "申请配送",
    "ru-RU": "Запросить доставку",
    "ar-SA": "اطلب توصيل",
    "hi-IN": "डिलीवरी का अनुरोध करें",
    "ko-KR": "배달 요청",
    "he-IL": "בקש משלוח",
    "uk-UA": "Замовити доставку",
    "id-ID": "Minta pengiriman",
    "th-TH": "ร้องขอการจัดส่ง"
  },
  "action_request_delivery_desc": {
    "pt-PT": "Envie e receba pacotes com rapidez, segurança e eficiência.",
    "pt-BR": "Envie e receba pacotes com rapidez, segurança e eficiência.",
    "en-US": "Send and receive packages quickly, safely, and efficiently.",
    "es-ES": "Envía y recibe paquetes de forma rápida, segura y eficiente.",
    "fr-FR": "Envoyez et recevez des colis rapidement, en toute sécurité et efficacement.",
    "de-DE": "Versenden und empfangen Sie Pakete schnell, sicher und effizient.",
    "it-IT": "Invia e ricevi pacchi in modo rapido, sicuro ed efficiente.",
    "ja-JP": "荷物を迅速、安全、効率的に送受信します。",
    "zh-CN": "快速、安全、高效地发送和接收包裹。",
    "ru-RU": "Отправляйте и получайте посылки быстро, безопасно и эффективно.",
    "ar-SA": "أرسل واستقبل الطرود بسرعة، أمان وكفاءة.",
    "hi-IN": "पैकेजों को जल्दी, सुरक्षित और कुशलता से भेजें और प्राप्त करें।",
    "ko-KR": "패키지를 빠르고 안전하며 효율적으로 보내고 받으세요.",
    "he-IL": "שלח וקבל חבילות במהירות, בבטחה וביעילות.",
    "uk-UA": "Відправляйте та отримуйте посилки швидко, безпечно та ефективно.",
    "id-ID": "Kirim dan terima paket dengan cepat, aman, dan efisien.",
    "th-TH": "ส่งและรับพัสดุได้อย่างรวดเร็ว ปลอดภัย และมีประสิทธิภาพ"
  },
  "btn_view_history": {
    "pt-PT": "Ver histórico",
    "pt-BR": "Ver histórico",
    "en-US": "View history",
    "es-ES": "Ver historial",
    "fr-FR": "Voir l'historique",
    "de-DE": "Verlauf anzeigen",
    "it-IT": "Visualizza cronologia",
    "ja-JP": "履歴を見る",
    "zh-CN": "查看历史记录",
    "ru-RU": "Посмотреть историю",
    "ar-SA": "عرض السجل",
    "hi-IN": "इतिहास देखें",
    "ko-KR": "기록 보기",
    "he-IL": "הצג היסטוריה",
    "uk-UA": "Переглянути історію",
    "id-ID": "Lihat riwayat",
    "th-TH": "ดูประวัติ"
  },
  "action_view_history_desc": {
    "pt-PT": "Consulte todas as suas viagens e entregas passadas.",
    "pt-BR": "Consulte todas as suas viagens e entregas passadas.",
    "en-US": "View all your past trips and deliveries.",
    "es-ES": "Consulta todos tus viajes y entregas pasados.",
    "fr-FR": "Consultez tous vos trajets et livraisons passés.",
    "de-DE": "Sehen Sie sich alle Ihre vergangenen Fahrten und Lieferungen an.",
    "it-IT": "Visualizza tutti i tuoi viaggi e le consegne passate.",
    "ja-JP": "過去のすべての旅行と配達を表示します。",
    "zh-CN": "查看您过去的所有行程和配送。",
    "ru-RU": "Просмотр всех ваших прошлых поездок и доставок.",
    "ar-SA": "عرض جميع رحلاتك وعمليات التوصيل السابقة.",
    "hi-IN": "अपनी सभी पिछली यात्राएं और डिलीवरी देखें।",
    "ko-KR": "과거의 모든 여행 및 배달 기록을 확인하세요.",
    "he-IL": "הצג את כל הנסיעות והמשלוחים הקודמים שלך.",
    "uk-UA": "Переглянути всі свої минулі поїздки та доставки.",
    "id-ID": "Lihat semua perjalanan dan pengiriman Anda sebelumnya.",
    "th-TH": "ดูประวัติการเดินทางและการจัดส่งทั้งหมดของคุณ"
  },
  "menu_wallet_swg": {
    "pt-PT": "Carteira",
    "pt-BR": "Carteira",
    "en-US": "Wallet",
    "es-ES": "Billetera",
    "fr-FR": "Portefeuille",
    "de-DE": "Brieftasche",
    "it-IT": "Portafoglio",
    "ja-JP": "ウォレット",
    "zh-CN": "钱包",
    "ru-RU": "Кошелек",
    "ar-SA": "المحفظة",
    "hi-IN": "वॉलेट",
    "ko-KR": "지갑",
    "he-IL": "ארנק",
    "uk-UA": "Гаманець",
    "id-ID": "Dompet",
    "th-TH": "กระเป๋าเงิน"
  },
  "quick_access_wallet_desc": {
    "pt-PT": "Veja o seu saldo, adicione dinheiro, gerencie métodos de pagamento e muito mais.",
    "pt-BR": "Veja seu saldo, adicione dinheiro, gerencie métodos de pagamento e muito mais.",
    "en-US": "View your balance, add money, manage payment methods, and more.",
    "es-ES": "Consulta tu saldo, añade dinero, gestiona métodos de pago y mucho más.",
    "fr-FR": "Consultez votre solde, ajoutez de l'argent, gérez les méthodes de paiement, et plus encore.",
    "de-DE": "Sehen Sie Ihr Guthaben, fügen Sie Geld hinzu, verwalten Sie Zahlungsmethoden und mehr.",
    "it-IT": "Visualizza il tuo saldo, aggiungi denaro, gestisci i metodi di pagamento e altro ancora.",
    "ja-JP": "残高の表示、お金の追加、支払い方法の管理など。",
    "zh-CN": "查看您的余额、充值、管理支付方式等等。",
    "ru-RU": "Просматривайте свой баланс, пополняйте счет, управляйте способами оплаты и многое другое.",
    "ar-SA": "عرض رصيدك، إضافة الأموال، إدارة طرق الدفع، والمزيد.",
    "hi-IN": "अपना बैलेंस देखें, पैसे जोड़ें, भुगतान के तरीकों का प्रबंधन करें, और बहुत कुछ।",
    "ko-KR": "잔액 확인, 충전, 결제 방법 관리 등을 할 수 있습니다.",
    "he-IL": "הצג את היתרה שלך, הוסף כסף, נהל אמצעי תשלום ועוד.",
    "uk-UA": "Переглядайте свій баланс, додавайте кошти, керуйте способами оплати тощо.",
    "id-ID": "Lihat saldo Anda, tambah uang, kelola metode pembayaran, dan lainnya.",
    "th-TH": "ดูยอดเงินของคุณ เพิ่มเงิน จัดการวิธีการชำระเงิน และอื่นๆ"
  },
  "btn_view_details": {
    "pt-PT": "Ver detalhes",
    "pt-BR": "Ver detalhes",
    "en-US": "View details",
    "es-ES": "Ver detalles",
    "fr-FR": "Voir les détails",
    "de-DE": "Details anzeigen",
    "it-IT": "Vedi dettagli",
    "ja-JP": "詳細を見る",
    "zh-CN": "查看详情",
    "ru-RU": "Просмотреть детали",
    "ar-SA": "عرض التفاصيل",
    "hi-IN": "विवरण देखें",
    "ko-KR": "세부 정보 보기",
    "he-IL": "הצג פרטים",
    "uk-UA": "Переглянути деталі",
    "id-ID": "Lihat detail",
    "th-TH": "ดูรายละเอียด"
  },
  "menu_history": {
    "pt-PT": "Histórico",
    "pt-BR": "Histórico",
    "en-US": "History",
    "es-ES": "Historial",
    "fr-FR": "Historique",
    "de-DE": "Verlauf",
    "it-IT": "Cronologia",
    "ja-JP": "履歴",
    "zh-CN": "历史记录",
    "ru-RU": "История",
    "ar-SA": "السجل",
    "hi-IN": "इतिहास",
    "ko-KR": "기록",
    "he-IL": "היסטוריה",
    "uk-UA": "Історія",
    "id-ID": "Riwayat",
    "th-TH": "ประวัติ"
  },
  "footer_copyright": {
    "pt-PT": "© 2024. Todos os direitos reservados.",
    "pt-BR": "© 2024. Todos os direitos reservados.",
    "en-US": "© 2024. All rights reserved.",
    "es-ES": "© 2024. Todos los derechos reservados.",
    "fr-FR": "© 2024. Tous droits réservés.",
    "de-DE": "© 2024. Alle Rechte vorbehalten.",
    "it-IT": "© 2024. Tutti i diritti riservati.",
    "ja-JP": "© 2024. 全著作権所有。",
    "zh-CN": "© 2024。保留所有权利。",
    "ru-RU": "© 2024. Все права защищены.",
    "ar-SA": "© 2024. جميع الحقوق محفوظة.",
    "hi-IN": "© 2024। सभी अधिकार सुरक्षित।",
    "ko-KR": "© 2024. 모든 권리 보유.",
    "he-IL": "© 2024. כל הזכויות שמורות.",
    "uk-UA": "© 2024. Всі права захищені.",
    "id-ID": "© 2024. Semua hak dilindungi undang-undang.",
    "th-TH": "© 2024. สงวนลิขสิทธิ์ทั้งหมด"
  },
  "login_button": {
    "pt-PT": "Iniciar Sessão",
    "pt-BR": "Entrar",
    "en-US": "Log in",
    "es-ES": "Iniciar sesión",
    "fr-FR": "Se connecter",
    "de-DE": "Anmelden",
    "it-IT": "Accedi",
    "ja-JP": "ログイン",
    "zh-CN": "登录",
    "ru-RU": "Войти",
    "ar-SA": "تسجيل الدخول",
    "hi-IN": "लॉग इन करें",
    "ko-KR": "로그인",
    "he-IL": "התחבר",
    "uk-UA": "Увійти",
    "id-ID": "Masuk",
    "th-TH": "เข้าสู่ระบบ"
  },
  "auth_dialog_switch_to_register": {
    "pt-PT": "Não tem uma conta? Registe-se",
    "pt-BR": "Não tem uma conta? Cadastre-se",
    "en-US": "Don't have an account? Register",
    "es-ES": "¿No tienes una cuenta? Regístrate",
    "fr-FR": "Vous n'avez pas de compte ? S'inscrire",
    "de-DE": "Kein Konto? Registrieren",
    "it-IT": "Non hai un account? Registrati",
    "ja-JP": "アカウントをお持ちでないですか？登録",
    "zh-CN": "没有账户？注册",
    "ru-RU": "Нет аккаунта? Зарегистрироваться",
    "ar-SA": "ليس لديك حساب؟ سجل",
    "hi-IN": "खाता नहीं है? रजिस्टर करें",
    "ko-KR": "계정이 없으신가요? 가입하기",
    "he-IL": "אין לך חשבון? הירשם",
    "uk-UA": "Не маєте облікового запису? Зареєструватися",
    "id-ID": "Belum punya akun? Daftar",
    "th-TH": "ยังไม่มีบัญชีใช่ไหม? ลงทะเบียน"
  },
  "auth_dialog_title_register": {
    "pt-PT": "Registo",
    "pt-BR": "Cadastro",
    "en-US": "Register",
    "es-ES": "Registro",
    "fr-FR": "Inscription",
    "de-DE": "Registrieren",
    "it-IT": "Registrazione",
    "ja-JP": "登録",
    "zh-CN": "注册",
    "ru-RU": "Регистрация",
    "ar-SA": "تسجيل",
    "hi-IN": "रजिस्टर करें",
    "ko-KR": "회원가입",
    "he-IL": "הרשמה",
    "uk-UA": "Реєстрація",
    "id-ID": "Daftar",
    "th-TH": "ลงทะเบียน"
  },
  "auth_dialog_desc_register_driver": {
    "pt-PT": "Introduza as suas informações para criar uma conta de motorista.",
    "pt-BR": "Insira suas informações para criar uma conta de motorista.",
    "en-US": "Enter your information to create a driver account.",
    "es-ES": "Introduce tu información para crear una cuenta de conductor.",
    "fr-FR": "Entrez vos informations pour créer un compte de chauffeur.",
    "de-DE": "Geben Sie Ihre Daten ein, um ein Fahrerkonto zu erstellen.",
    "it-IT": "Inserisci le tue informazioni per creare un account conducente.",
    "ja-JP": "運転手アカウントを作成するには、情報を入力してください。",
    "zh-CN": "输入您的信息以创建司机账户。",
    "ru-RU": "Введите вашу информацию для создания аккаунта водителя.",
    "ar-SA": "أدخل معلوماتك لإنشاء حساب سائق.",
    "hi-IN": "एक ड्राइवर खाता बनाने के लिए अपनी जानकारी दर्ज करें।",
    "ko-KR": "운전자 계정을 만들려면 정보를 입력하세요.",
    "he-IL": "הזן את המידע שלך כדי ליצור חשבון נהג.",
    "uk-UA": "Введіть свої дані для створення облікового запису водія.",
    "id-ID": "Masukkan informasi Anda untuk membuat akun pengemudi.",
    "th-TH": "กรอกข้อมูลของคุณเพื่อสร้างบัญชีคนขับ"
  },
  "name_label": {
    "pt-PT": "Nome",
    "pt-BR": "Nome",
    "en-US": "Name",
    "es-ES": "Nombre",
    "fr-FR": "Nom",
    "de-DE": "Name",
    "it-IT": "Nome",
    "ja-JP": "名前",
    "zh-CN": "姓名",
    "ru-RU": "Имя",
    "ar-SA": "الاسم",
    "hi-IN": "नाम",
    "ko-KR": "이름",
    "he-IL": "שם",
    "uk-UA": "Ім'я",
    "id-ID": "Nama",
    "th-TH": "ชื่อ"
  },
  "confirm_password_label": {
    "pt-PT": "Confirmar palavra-passe",
    "pt-BR": "Confirmar senha",
    "en-US": "Confirm password",
    "es-ES": "Confirmar contraseña",
    "fr-FR": "Confirmer le mot de passe",
    "de-DE": "Passwort bestätigen",
    "it-IT": "Conferma password",
    "ja-JP": "パスワードを再入力",
    "zh-CN": "确认密码",
    "ru-RU": "Подтвердите пароль",
    "ar-SA": "تأكيد كلمة المرور",
    "hi-IN": "पासवर्ड की पुष्टि करें",
    "ko-KR": "비밀번호 확인",
    "he-IL": "אשר סיסמה",
    "uk-UA": "Підтвердити пароль",
    "id-ID": "Konfirmasi kata sandi",
    "th-TH": "ยืนยันรหัสผ่าน"
  },
  "register_button": {
    "pt-PT": "Registar",
    "pt-BR": "Cadastrar",
    "en-US": "Register",
    "es-ES": "Registrarse",
    "fr-FR": "S'inscrire",
    "de-DE": "Registrieren",
    "it-IT": "Registrati",
    "ja-JP": "登録",
    "zh-CN": "注册",
    "ru-RU": "Зарегистрироваться",
    "ar-SA": "تسجيل",
    "hi-IN": "रजिस्टर करें",
    "ko-KR": "회원가입",
    "he-IL": "הירשם",
    "uk-UA": "Зареєструватися",
    "id-ID": "Daftar",
    "th-TH": "ลงทะเบียน"
  },
  "auth_dialog_switch_to_login": {
    "pt-PT": "Já tem uma conta? Inicie sessão",
    "pt-BR": "Já tem uma conta? Faça login",
    "en-US": "Already have an account? Log in",
    "es-ES": "¿Ya tienes una cuenta? Inicia sesión",
    "fr-FR": "Vous avez déjà un compte ? Se connecter",
    "de-DE": "Haben Sie bereits ein Konto? Anmelden",
    "it-IT": "Hai già un account? Accedi",
    "ja-JP": "すでにアカウントをお持ちですか？ログイン",
    "zh-CN": "已有账户？登录",
    "ru-RU": "Уже есть аккаунт? Войти",
    "ar-SA": "لديك حساب بالفعل؟ سجل الدخول",
    "hi-IN": "पहले से ही एक खाता है? लॉग इन करें",
    "ko-KR": "이미 계정이 있으신가요? 로그인",
    "he-IL": "כבר יש לך חשבון? התחבר",
    "uk-UA": "Вже маєте обліковий запис? Увійдіть",
    "id-ID": "Sudah punya akun? Masuk",
    "th-TH": "มีบัญชีอยู่แล้วใช่ไหม? เข้าสู่ระบบ"
  },
  "role_driver": {
    "pt-PT": "Motorista",
    "pt-BR": "Motorista",
    "en-US": "Driver",
    "es-ES": "Conductor",
    "fr-FR": "Chauffeur",
    "de-DE": "Fahrer",
    "it-IT": "Autista",
    "ja-JP": "運転手",
    "zh-CN": "司机",
    "ru-RU": "Водитель",
    "ar-SA": "سائق",
    "hi-IN": "ड्राइवर",
    "ko-KR": "운전기사",
    "he-IL": "נהג",
    "uk-UA": "Водій",
    "id-ID": "Pengemudi",
    "th-TH": "คนขับ"
  },
  "btn_driver_desc": {
    "pt-PT": "Seja o seu próprio patrão. Dirija e ganhe dinheiro quando quiser.",
    "pt-BR": "Seja seu próprio chefe. Dirija e ganhe dinheiro quando quiser.",
    "en-US": "Be your own boss. Drive and earn money whenever you want.",
    "es-ES": "Sé tu propio jefe. Conduce y gana dinero cuando quieras.",
    "fr-FR": "Soyez votre propre patron. Conduisez et gagnez de l'argent quand vous le souhaitez.",
    "de-DE": "Seien Sie Ihr eigener Chef. Fahren Sie und verdienen Sie Geld, wann immer Sie wollen.",
    "it-IT": "Sii il capo di te stesso. Guida e guadagna quando vuoi.",
    "ja-JP": "自分の上司になりましょう。好きなときに運転して稼ぎましょう。",
    "zh-CN": "做你自己的老板。随时随地开车赚钱。",
    "ru-RU": "Будьте себе начальником. Водите и зарабатывайте деньги, когда захотите.",
    "ar-SA": "كن سيد نفسك. قد واكسب المال وقتما تشاء.",
    "hi-IN": "अपने खुद के बॉस बनें। जब चाहें गाड़ी चलाएं और पैसे कमाएं।",
    "ko-KR": "자신의 사장이 되어 보세요. 원할 때 언제든지 운전하고 돈을 벌 수 있습니다.",
    "he-IL": "היה הבוס של עצמך. סע והרוויח כסף מתי שתרצה.",
    "uk-UA": "Будьте своїм власним босом. Керуйте авто і заробляйте гроші, коли забажаєте.",
    "id-ID": "Jadilah bos bagi diri Anda sendiri. Mengemudi dan dapatkan uang kapan pun Anda mau.",
    "th-TH": "เป็นเจ้านายของตัวเอง ขับรถและสร้างรายได้เมื่อคุณต้องการ"
  },
  "role_passenger": {
    "pt-PT": "Passageiro",
    "pt-BR": "Passageiro",
    "en-US": "Passenger",
    "es-ES": "Pasajero",
    "fr-FR": "Passager",
    "de-DE": "Passagier",
    "it-IT": "Passeggero",
    "ja-JP": "乗客",
    "zh-CN": "乘客",
    "ru-RU": "Пассажир",
    "ar-SA": "راكب",
    "hi-IN": "यात्री",
    "ko-KR": "승객",
    "he-IL": "נוסע",
    "uk-UA": "Пасажир",
    "id-ID": "Penumpang",
    "th-TH": "ผู้โดยสาร"
  },
  "btn_passenger_desc": {
    "pt-PT": "Viagem rápida, acessível e segura, a qualquer hora e em qualquer lugar.",
    "pt-BR": "Viagem rápida, acessível e segura, a qualquer hora e em qualquer lugar.",
    "en-US": "Fast, affordable, and safe trips, anytime and anywhere.",
    "es-ES": "Viajes rápidos, asequibles y seguros, en cualquier momento y lugar.",
    "fr-FR": "Des trajets rapides, abordables et sûrs, à tout moment et n'importe où.",
    "de-DE": "Schnelle, erschwingliche und sichere Fahrten, jederzeit und überall.",
    "it-IT": "Viaggi veloci, convenienti e sicuri, in qualsiasi momento e ovunque.",
    "ja-JP": "いつでもどこでも、速くて手頃な価格で安全な旅を。",
    "zh-CN": "随时随地享受快速、实惠、安全的出行。",
    "ru-RU": "Быстрые, доступные и безопасные поездки, в любое время и в любом месте.",
    "ar-SA": "رحلات سريعة، ميسورة التكلفة وآمنة، في أي وقت وفي أي مكان.",
    "hi-IN": "कहीं भी, कभी भी तेज़, किफायती और सुरक्षित यात्राएं।",
    "ko-KR": "언제 어디서나 빠르고 저렴하며 안전한 여행.",
    "he-IL": "נסיעות מהירות, משתלמות ובטוחות, בכל זמן ובכל מקום.",
    "uk-UA": "Швидкі, доступні та безпечні поїздки, будь-коли та будь-де.",
    "id-ID": "Perjalanan cepat, terjangkau, dan aman, kapan saja dan di mana saja.",
    "th-TH": "เดินทางได้รวดเร็ว ราคาไม่แพง และปลอดภัย ทุกที่ทุกเวลา"
  },
  "welcome_title_p3": {
    "pt-PT": "Conectanto Voce Globalmente",
    "pt-BR": "Viagens feitas para você",
    "en-US": "Trips made for you",
    "es-ES": "Viajes hechos para ti",
    "fr-FR": "Des trajets faits pour vous",
    "de-DE": "Fahrten, die für Sie gemacht wurden",
    "it-IT": "Viaggi fatti apposta per te",
    "ja-JP": "あなたのために作られた旅",
    "zh-CN": "为您量身定制的旅行",
    "ru-RU": "Поездки, созданные для вас",
    "ar-SA": "رحلات مصممة خصيصًا لك",
    "hi-IN": "आप के लिए बनी यात्राएं",
    "ko-KR": "당신을 위해 만들어진 여행",
    "he-IL": "נסיעות שנעשו בשבילך",
    "uk-UA": "Поїздки, створені для вас",
    "id-ID": "Perjalanan yang dibuat untuk Anda",
    "th-TH": "ทริปที่สร้างมาเพื่อคุณ"
  },
  "welcome_subtitle": {
    "pt-PT": "A maneira mais fácil de se mover na cidade.",
    "pt-BR": "A maneira mais fácil de se mover na cidade.",
    "en-US": "The easiest way to move around the city.",
    "es-ES": "La forma más fácil de moverse por la ciudad.",
    "fr-FR": "La façon la plus simple de se déplacer en ville.",
    "de-DE": "Die einfachste Art, sich in der Stadt fortzubewegen.",
    "it-IT": "Il modo più semplice per muoversi in città.",
    "ja-JP": "街中を移動する最も簡単な方法。",
    "zh-CN": "在城市中出行的最简单方式。",
    "ru-RU": "Самый простой способ передвигаться по городу.",
    "ar-SA": "أسهل طريقة للتنقل في المدينة.",
    "hi-IN": "शहर में घूमने का सबसे आसान तरीका।",
    "ko-KR": "도시를 돌아다니는 가장 쉬운 방법.",
    "he-IL": "הדרך הקלה ביותר להתנייד בעיר.",
    "uk-UA": "Найпростіший спосіб пересуватися містом.",
    "id-ID": "Cara termudah untuk berkeliling kota.",
    "th-TH": "วิธีที่ง่ายที่สุดในการเดินทางรอบเมือง"
  },
  "landing_auth_title": {
    "pt-PT": "Entre na sua conta",
    "pt-BR": "Acesse sua conta",
    "en-US": "Access your account",
    "es-ES": "Accede a tu cuenta",
    "fr-FR": "Accédez à votre compte",
    "de-DE": "Greifen Sie auf Ihr Konto zu",
    "it-IT": "Accedi al tuo account",
    "ja-JP": "アカウントにアクセス",
    "zh-CN": "访问您的账户",
    "ru-RU": "Войдите в свой аккаунт",
    "ar-SA": "ادخل إلى حسابك",
    "hi-IN": "अपने खाते तक पहुंचें",
    "ko-KR": "계정에 접속",
    "he-IL": "גש לחשבון שלך",
    "uk-UA": "Увійдіть до свого облікового запису",
    "id-ID": "Akses akun Anda",
    "th-TH": "เข้าถึงบัญชีของคุณ"
  },
  "btn_fleet_manager_title": {
    "pt-PT": "Gestor de Frota",
    "pt-BR": "Gestor de Frota",
    "en-US": "Fleet Manager",
    "es-ES": "Gerente de flota",
    "fr-FR": "Gestionnaire de flotte",
    "de-DE": "Flottenmanager",
    "it-IT": "Responsabile della flotta",
    "ja-JP": "フリートマネージャー",
    "zh-CN": "车队经理",
    "ru-RU": "Менеджер автопарка",
    "ar-SA": "مدير الأسطول",
    "hi-IN": "फ्लीट मैनेजर",
    "ko-KR": "차량 관리자",
    "he-IL": "מנהל צי רכב",
    "uk-UA": "Менеджер автопарку",
    "id-ID": "Manajer Armada",
    "th-TH": "ผู้จัดการกองยาน"
  },
  "btn_fleet_manager_desc": {
    "pt-PT": "Gerencie a sua frota de veículos e motoristas",
    "pt-BR": "Gerencie sua frota de veículos e motoristas",
    "en-US": "Manage your fleet of vehicles and drivers",
    "es-ES": "Administra tu flota de vehículos y conductores",
    "fr-FR": "Gérez votre flotte de véhicules et de chauffeurs",
    "de-DE": "Verwalten Sie Ihre Fahrzeugflotte und Fahrer",
    "it-IT": "Gestisci la tua flotta di veicoli e autisti",
    "ja-JP": "車両とドライバーのフリートを管理する",
    "zh-CN": "管理您的车队和司机",
    "ru-RU": "Управляйте своим автопарком и водителями",
    "ar-SA": "إدارة أسطول المركبات والسائقين الخاص بك",
    "hi-IN": "अपने वाहनों और ड्राइवरों के बेड़े का प्रबंधन करें",
    "ko-KR": "차량 및 운전자 차량을 관리하세요",
    "he-IL": "נהל את צי הרכב והנהגים שלך",
    "uk-UA": "Керуйте своїм автопарком і водіями",
    "id-ID": "Kelola armada kendaraan dan pengemudi Anda",
    "th-TH": "จัดการกองยานพาหนะและคนขับของคุณ"
  }
}
export const languages = [
    { value: "pt-PT", label: "Português (Portugal)", flagCode: "pt", currency: { code: "EUR", symbol: "€" } },
    { value: "pt-BR", label: "Português (Brasil)", flagCode: "br", currency: { code: "BRL", symbol: "R$" } },
    { value: "en-US", label: "English", flagCode: "us", currency: { code: "USD", symbol: "$" } },
    { value: "es-ES", label: "Español", flagCode: "es", currency: { code: "EUR", symbol: "€" } },
    { value: "fr-FR", label: "Français", flagCode: "fr", currency: { code: "EUR", symbol: "€" } },
    { value: "de-DE", label: "Deutsch", flagCode: "de", currency: { code: "EUR", symbol: "€" } },
    { value: "it-IT", label: "Italiano", flagCode: "it", currency: { code: "EUR", symbol: "€" } },
    { value: "ja-JP", label: "日本語", flagCode: "jp", currency: { code: "JPY", symbol: "¥" } },
    { value: "zh-CN", label: "中文", flagCode: "cn", currency: { code: "CNY", symbol: "¥" } },
    { value: "ru-RU", label: "Русский", flagCode: "ru", currency: { code: "RUB", symbol: "₽" } },
    { value: "ar-SA", label: "العربية", flagCode: "sa", currency: { code: "SAR", symbol: "ر.س" } },
    { value: "hi-IN", label: "हिन्दी", flagCode: "in", currency: { code: "INR", symbol: "₹" } },
    { value: "ko-KR", label: "한국어", flagCode: "kr", currency: { code: "KRW", symbol: "₩" } },
    { value: "he-IL", label: "עברית", flagCode: "il", currency: { code: "ILS", symbol: "₪" } },
    { value: "uk-UA", label: "Українська", flagCode: "ua", currency: { code: "UAH", symbol: "₴" } },
    { value: "id-ID", label: "Bahasa Indonesia", flagCode: "id", currency: { code: "IDR", symbol: "Rp" } },
    { value: "th-TH", label: "ภาษาไทย", flagCode: "th", currency: { code: "THB", symbol: "฿" } },
    
];
export type TranslationKeys = keyof typeof translations;

  
